
name: Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
        
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  REPO_URL_LIENOL: https://github.com/Lienol/openwrt
  REPO_BRANCH_LIENOL: 21.02
  REPO_URL_IMMORTALWRT: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH_IMMORTALWRT: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  TZ: Asia/Shanghai
  DEVICE1: new3
  DEVICE2: r3g
  DEVICE3: n1-docker
  DEVICE4: n1-flash
  UPLOAD_DOCKERHUB: true
  UPLOAD_OUTPUT: true

jobs:
   new3:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 90
          keep_minimum_runs: 10
